### ISSUE TITLE
RowanSample* projects should be auto-loaded for tests

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#366]
I saw the test failure below when running the RwRowanProjectIssuesTest suite of tests. 
The test seems to expect RowanSample3 project to be loaded. 

I'm not sure what the best solution is, but it seems to me that a test should know if it needs a RowanSample* project loaded and if it does, load it automatically. 

(Note that the Rowan Services tests have the same problem. Many rely on RowanSample1 to be present but it's not obvious.) 

Assigning to Dale for ideas and proposals. 

```RwRowanProjectIssuesTest>>testIssue150_branches fails

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_HOME/Rowan/test/testRepositories/repos//RowanSample3; git --git-dir $ROWAN_PROJECTS_HOME/Rowan/test/testRepositories/repos//RowanSample3/.git --work-tree 

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_
UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitcheckoutIn:with: @2 line 3
RowanProjectService >> checkout: @6 line 6
RwRowanProjectIssuesTest >> testIssue150_branches @22 line 26
RwRowanProjectIssuesTest (TestCase) >> performTest @3 line 2
[] in  ExecBlock0 (TestCase) >> runCase @3 line 5
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwRowanProjectIssuesTest (TestCase) >> runCase @4 line 6
[] in  ExecBlock0 (TestCase) >> debug @4 line 2
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwRowanProjectIssuesTest (TestCase) >> debug @2 line 3
RwRowanProjectIssuesTest class (TestCase class) >> debug: @3 line 3
JadeServer64bit32 (JadeServer) >> debugTestNamed:of: @4 line 4
GsNMethod class >> _gsReturnToC @1 line 1```

**Comment by dalehenrich** [comment]
This test does not fail for me when run in Jadeite or topaz, so there must be something in your environment that causes the failure, so I will have to debug this when I am in the office ...

Test #150 was explicitly written to simply run the set of git commands that were being used to make sure that Rowan worked correctly with particular git commands ... the fact that the git command on you box is failing means that you are using a different version of git (older?/newer?) than the one we have been using ...

The precise error message should be in a Transcript or error log ... and that error message would be useful for figuring out what's up on your machine ...

The test is doing a clone of RowanSample3, so your supposition that it needs to be installed is not quite right ... I don't believe that RowanSample3 is actually loaded, but it is cloned so that we can have an example git repository to work with ...

**Comment by ericwinger** [comment]
> The test is doing a clone of RowanSample3, so your supposition that it needs to be installed is not quite right ...

Understood.  As you suggest, we can debug the specific test failure when you're in the office. 

@dalehenrich  A thought occurs, however. If Rowan requires that a minimum version of git is present, perhaps we need an explicit test for that. Does one already exist?

**Comment by dalehenrich** [comment]
Before jumping to conclusions, let's find out what is going wrong with your command ... it is just a standard clone that you use all the time to load RowanSample1 in Jadeite, so the root cause is likely to be some other issue...

Issue #150 mentions git 1.7.1 which is pretty old ... I am using 2.7.4  ... You haven't mentioned exactly how you are running your tests, but i'm guessing you are doing it in Jadeite ... so the git version is not likely to be the problem otherwise you would have seen a problem before now ...

**Comment by ericwinger** [comment]
The problem was a corrupted RowanSample3 directory on my local machine and the test ``testIssue150_branches`` did not clean itself up properly. 

- [ ] The quick fix is to remove the RowanSample3 directory. 
- [ ] Create a new issue to test any use of ``gitTools`` from services code. (That's why this test was written in the first place (#150).

**Comment by ericwinger** [comment]
Added #382
