### ISSUE TITLE
Should be able to always unload project

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#387]
Using a script slightly modified from #384, I created a rowan project with:

- 500 packages
- randomly up to 10 classes in each package
- randomly up to 30 methods in each package

When I try to unload the project using Jadeite, I get the following message and lose my session: 

![image](https://user-images.githubusercontent.com/36212516/47591123-551f5680-d923-11e8-9783-1a26f5c3912f.png)

Seems like it should be possible to unload a project no matter the size.

If it matters, ``GEM_TEMPOBJ_CACHE_SIZE=175000``

**Comment by dalehenrich** [comment]
I agree ... however it will require some creativity. 

The simplest solution would be to either do periodic commits at strategic places or to commit in response to an almost out of memory notification... but if a load hits an error after one of these *strategic commit* we will leave the system in partially unloaded state which is not cool ... Not to mention the fact that I don't want Rowan doing any commits at all ...

It's interesting to note that I wasn't able to load the project without intermediate commits, but I did the commits on package boundaries ... and that only worked because I knew that every package was ...

... now that I think about it ... There is `Rowan projectTools delete forceDeleteProjectNamed: ''` that just goes around and nukes the project from the loaded data structures ... I'll see if this method works to delete a large project ... 

If force delete works, how would you want to present that option to the user?

**Comment by ericwinger** [comment]
Opened https://github.com/GemTalk/Jadeite/issues/259 to add the menu option.
