### ISSUE TITLE
Class rename also updates method sends (jadeite issue #513)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#509]
This issue reported on Jadeite, but due to underlying Rowan functionality; cf https://github.com/GemTalk/Jadeite/issues/513

If you have a method send within a method that is the same as the class name, the method name gets updated.

The class is named ``RenameTest``.
instance methods:
```
RenameTest
^self class
test
^self RenameTest
```

When I renamed ``RenameTest`` to ``NewName``,
the ``RenameTest`` method was unchanged.
the test method was updated:
```test
^self NewName
```
which will fail since there's no method ``NewName``.

**Comment by dalehenrich** [comment]
@LisaAlmarode, I'm afraid that @ericwinger is mistaken in thinking that Rowan is making changes to methods. If you look at [RowanClassService >> renameClass:to:](https://github.com/GemTalk/Rowan/blob/candidateV1.2/rowan/src/Rowan-Services-Core/RowanClassService.class.st#L809-L827), you'll see that it is the RowanClassService code that is doing a [replaceSubString:in:with:](https://github.com/GemTalk/Rowan/blob/candidateV1.2/rowan/src/Rowan-Services-Core/RowanClassService.class.st#L815-L818) and then recompiling the method ... so this is Jadeite code written by @ericwinger that is incorrectly renaming a selector instead of a class ... Rowan is certainly recompiling these methods but the (incorrect) new source is generated by the RowanClassService code

**Comment by ericwinger** [comment]
Yes, @dalehenrich  is correct. I made a mistake and have made an initial improvement in the commit referenced in this commit https://github.com/GemTalk/Jadeite/issues/513#issuecomment-537621158
