### ISSUE TITLE
Would like api for getting all packages in a component tree

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#662]
There is a method `RwAbstractSimpleProjectLoadComponentV2>>packageNames` for getting the names of all the packages defined in a component. It would be helpful to have a method for getting all the package names in a component, as well as it's subcomponents. Perhaps, `allPackageNames`.

**Comment by dalehenrich** [comment]
following the pattern of #subcomponentsOf:, I'm going to add the `all package names` method to RwProject ... something along the lines of `allPackagesIn: componentName` ... Will you want an `ifNone:` variant or is an empty list sufficient?

Also, since component references can recurse, my first cut may or may not be `infinite loop proof` ...

**Comment by dalehenrich** [comment]
done ... add RwProject>>allPackageNamesIn: that takes a name or an array of names

**Comment by ericwinger** [comment]
Minor issue but worth correcting. The new method is actually named `allPackgeNamesIn:` (no second 'a' in Packge). 

![image](https://user-images.githubusercontent.com/36212516/99597591-139bf100-29ad-11eb-9769-f696caa71f2b.png)

**Comment by dalehenrich** [comment]
oops

**Comment by dalehenrich** [comment]
fixed spelling of `allPackageNamesIn:`
