### ISSUE TITLE
components not in sync

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#784]
Remove a component using `RwDefinedProject>>removeComponentNamed:` 

The component is removed from the underlying `RwResolvedProjectComponentsV2`, but `RwDefinedProject>>componentNames` still shows the component present. 

Removing the 'def' component from the project.  First screen grab shows that 'def' component is not present. 
![image](https://user-images.githubusercontent.com/36212516/149241150-7410e05f-9419-4678-8996-8ce603f82b38.png)

Second screen grab shows that the project still has `def` returned from `componentNames` 

![image](https://user-images.githubusercontent.com/36212516/149241008-d47e513b-0835-4876-8a39-fe417bc1db71.png)

**Comment by dalehenrich** [comment]
You don't happen to have a simple workspace doit that reproduces the problem, do you? If not, I can splash around trying to reproduce the problem and let you know if I have trouble ...

Could you include a screen shot of the project list, so I can match up the versions that you are using with the version that I will run my tests with?

**Comment by ericwinger** [comment]
I don't have a simple workspace reproduction case. I can try to recreate one though if the following doesn't help. 

I'm using `RowanSample9`, got it's definition, then just added and removed a new component.  Add was done with `addLoadComponentNamed:`. 

The code I'm using was just pushed to github in the `eric_component_V3.0` branch, sha `d4da096`.  Class is `RowanProjectDefinitionService`

**Comment by dalehenrich** [comment]
what branch of `RowanSample9` are you using? There are about 60 branches :) ... also the SHA of the Rowan that you are using would help as well ... Thanks ... finally is this bug blocking your work? If it is I will drop what I'm doing and start fixing this immediately (or close to it) ... otherwise I will get to a stopping point with my current work and then tackle this bug ...

**Comment by ericwinger** [comment]
Ahh, yes. Sha & branch would help.   

Rowan branch: `eric_component_V3.0` sha: `ea52653`
RowanClientServices branch: `eric_component_V3.0` sha: `d4da096`

I'm not blocked immediately. If your 'stopping point' is within a couple days that would be fine.

**Comment by dalehenrich** [comment]
Sound good ... do you have the RowanSample9 branch that you are using?

**Comment by ericwinger** [comment]
RowanSample9 branch: `spec_0061` sha: `6b72522`

**Comment by dalehenrich** [comment]
Here's a simple test case that reproduces the problem:
```smalltalk
| spec projects project |
spec := RwSpecification fromUrl:'file:$GS_HOME/shared/repos/RowanSample9/specs/spec_0061.ston'.
spec projectsHome: '/home/dhenrich/rogue/_homes/rogue/_home/server/stones/rowan_dev_l/git'.
projects := spec resolveStrict load.
project := projects projectNamed: spec projectName.
project addLoadComponentNamed: 'def'.
project componentNames.
"================"
(Rowan projectNamed: 'RowanSample9') defined
	removeComponentNamed: 'def';
	componentNames.
```
Now the interesting issue is that there are two places where component names are managed: the component structure (RwResolvedProjectComponentsV2) and the list of component names to be loaded in the load spec (RwLoadSpecificationV2) and the #componentNames selector accesses the list in the load spec ... #removeComponentNamed: DOES NOT remove the named component from the list in the load spec, which is the root cause of the bug...

**Comment by dalehenrich** [comment]
@ericwinger you should be able to merge the latest masterV3.0 into your branch and load into your image to get the fix.
