### ISSUE TITLE
Comment isn't written to disk in an expected place

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#793]
If I send `RwDefinedProject>>comment:` to the project definition and then export the project definition to disk, I don't see the new comment on the command line after doing a `git diff`. Git diff was done from the `$ROWAN_PROJECTS_HOME/RowanSample9` directory on disk. 

No errors happened during the sending of `comment:`

**Comment by dalehenrich** [comment]
Ah ... so the #comment: is recorded in the load spec of the project ... and to record the load spec on disk you have to use #exportLoadSpecification ... that's why I asked where you expect to see the comment ... the load spec seems to be the only object that developers are expected to see in it's native form and I think that a comment of some form that is visible on disk is important ... I'm open to renaming the selector if you think that would be more obvious ... 

I think the load spec is the good choice for the repository of the comment and I suppose it would be useful to show it when the project is selected along with the name, sha, etc. .... but again we may want to be explicit that it is a comment in the load spec ?

We can talk this over more and flip some coins ...

**Comment by dalehenrich** [comment]
... with the load spec accessible in the IDE, perhaps I can completely eliminate the generic #comment: message in the RwAbstractProject hierarchy ...

**Comment by ericwinger** [comment]
> I think that a comment of some form that is visible on disk is important ... I'm open to renaming the selector if you think that would be more obvious ...

If we're limiting comments to the load spec only then I would consider `loadSpecComment`

**Comment by dalehenrich** [comment]
I think we resolved this issue as well ... the sending comment to a RwProject updates just the load spec comment and load spec needs to be exported to save on disk ... when doing object specific windows, the comment field should be updated sending messages directly to the objects ...
