### ISSUE TITLE
`allusers` considered dangerous ... adding a new package to a symbol dictionary that has existing packages associated with `allusers` can cause all of the existing packages to be removed on reload

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#809]
Reproduction steps: 
- Reload RowanClientServices from disk. Make sure the disk has no diffs `git diff` 
- Add new package to RowanClientServices
-- Component name: `common/platforms/gemstone/Services`
-- Symbol dictionary: `RowanTools`
-- Package name: `Rowan-Services-Tools-Extensions`
- Create new method in classes `RwLoadComponent` and `RwSubcomponent>>isSubcomponent` (package is `Rowan-Components`)
- Move methods to the new package
- Run `Changes` on project `RowanClientServices` 
- Get error looking up class `JadeServer` - Note that JadeServer should not have been touched during the above steps. It must be available in UserGlobals for Jadeite to work.  It is an entry point from client services to server services and is always available. If you abort after the above steps, Changes works fine and JadeServer is present in UserGlobals once again. 
[20220404_key_not_found_error.txt](https://github.com/GemTalk/Rowan/files/8412150/20220404_key_not_found_error.txt)

**Comment by dalehenrich** [comment]
Does changes work immediately after login ... BEFORE you monkey with methods? ... I can't imagine anything in the Rowan move method logic that would remove the JadeServer class from UserGlobals  (but maybe I'm not imaginative enough)  ...

**Comment by ericwinger** [comment]
> Does changes work immediately after login ... BEFORE you monkey with methods? 
Yes. Also, after I abort.  
>I can't imagine anything in the Rowan move method logic that would remove the JadeServer class from UserGlobals (but maybe I'm not imaginative enough) 
I'm baffled, too. And my code is not above suspicion. I was able to reproduce this twice with the steps above. 

Going to investigate more.

**Comment by ericwinger** [comment]
The two primary methods involved, for possibly reproducing outside Jadeite, are: 
```
RwProject>>addNewPackageNamed:inSybolDictionaryNamed:toComponentNamed:
theClass >>rwMoveMethod:toPackage:
```

**Comment by dalehenrich** [comment]
Velly intelesting ... now I will probably need a picture of your project list so that I can set the image up exactly like you've got it ... because that code has no business removing JadeServer from UserGlobals :) ... It will take me a while to get my own Rowan v3.0 development environment set up, but this will be an interesting problem to get to the bottom of :)

**Comment by dalehenrich** [comment]
Okay it is IS reproducing with current masterV3.0 ... so the hunt commences ...

**Comment by dalehenrich** [comment]
The root cause of this bug is that the RowanKernel symbol dictionary has packages defined against it using `allusers` ... in the example above the default username is `SystemUser` ... in the lookup code (during a load), the use of `SystemUser` a more specific username than `allusers` is used in favor of `allusers` which in this case causes all of the original packages in RowanKernel to be removed from the system ... so JadeServer was not the only casualty ... nearly all of Rowan was removed :) ... so I need to rethink the existence of `allusers` and friends ...

**Comment by dalehenrich** [comment]
as I dig into this the issue is a bit deeper than just `allusers` ... in the RowanClientServices case, there **IS** an entry for `SystemUser`, however, it does not have an entry for the package `Rowan-JadeServer`, while the entry for `allusers` does have an entry for `Rowan-JadeServer`...
