### ISSUE TITLE
No default package after rowan installed 

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#96]
Login to a freshly rowanized stone.
Go to classes browser, Dictionaries pane, create new Dictionary, define a class.
Get walkback:
a UserDefinedError occurred (error 2318), reason:halt, No package named nil found

**Comment by LisaAlmarode** [comment]
I was wrong about the problem - apparently the category needs to match an existing package name, so the problem was that no package was selected. 

It does get an error when I attempt to create a new package, with no default project.  

No error occurs when I attempt to add a package with an existing name, but nothing bad seems to happen.. 

I don't see a way that given a package, you can figure out what project it's in.

**Comment by dalehenrich** [comment]
don't know if this is a jadeite or rowan issue or just a "to be fixed in pyrite" ... @ericwinger can you figure this out?

**Comment by LisaAlmarode** [comment]
As you can tell, there was some confusion when I filed this. 
The nil isn't the problem... When you attempt to create a class where the category is nil (or any invalid package name), you should detect that and give a nice dialog saying "Invalid category name (nil): you must set category to a valid package name"

**Comment by dalehenrich** [comment]
That is code that is executed by Rowan in the server and this is a use case for some sort of GsInteraction ... probably an #inform: (which should be logging a message when in non-interactive session) followed by the #error: ... this can be put in for Alpha1.1, but in Alpha1.1 you'll get the same behavior -- until pyrite maps interactions to dialog boxes ... labeling as First Release and assigning to me , since I have to put the interaction code in place ...

**Comment by dalehenrich** [comment]
looks like it is fixed
